# Generated by Django 4.2.5 on 2023-10-05 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post_thoughts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thoughts',
            name='shared_with',
            field=models.ManyToManyField(related_name='thought', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='thoughts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='thoughts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post_thoughts.thoughts'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
