# Generated by Django 4.2.5 on 2023-10-07 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post_thoughts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thought',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to=None)),
                ('shared_with', models.ManyToManyField(related_name='thoughts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='thoughts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post_thoughts.thought'),
        ),
        migrations.DeleteModel(
            name='Thoughts',
        ),
    ]
