# Generated by Django 4.2.5 on 2023-10-08 11:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post_thoughts', '0003_thought_alter_comment_thoughts_delete_thoughts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thought',
            name='shared_with',
            field=models.ManyToManyField(blank=True, null=True, related_name='thoughts', to=settings.AUTH_USER_MODEL),
        ),
    ]
