# Generated by Django 4.2.5 on 2023-10-08 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_thoughts', '0005_thought_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thought',
            old_name='body',
            new_name='thought',
        ),
    ]
