# Generated by Django 4.2.5 on 2023-10-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_thoughts', '0006_rename_body_thought_thought'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thought',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
