# Generated by Django 4.2.6 on 2023-10-09 12:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post_thoughts', '0007_alter_thought_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thought',
            name='shared_with',
            field=models.ManyToManyField(related_name='thoughts', to=settings.AUTH_USER_MODEL),
        ),
    ]
