# Generated by Django 4.2.4 on 2023-10-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_thoughts', '0008_alter_thought_shared_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='thought',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
