# Generated by Django 4.2.6 on 2023-10-15 23:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post_thoughts', '0010_comment_created_at_thought_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thought',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='share_thoughts', to=settings.AUTH_USER_MODEL),
        ),
    ]
